sudo: required
dist: trusty
language: php
php:
  - "7.2"
  - "7.1"

cache:
  direcrories:
    - $HOME/vendor
services:
  - docker

install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - cat Dockerfile
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION}

script:
  - travis_wait 20 docker-compose up --exit-code-from php
