name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
        os: ['ubuntu-latest']
        mongodb: ['4.0', '4.2']
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3307:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: 'unittest'
          MYSQL_ROOT_PASSWORD:
    name: PHP v${{ matrix.php }} with Mongo v${{ matrix.mongodb }}

    steps:
    - uses: actions/checkout@v1
    - name: Show PHP version
      run: php${{ matrix.php }} -v && composer -V
    - name: Show Docker version
      run: if [[ "$DEBUG" == "true" ]]; then docker version && env; fi
      env:
        DEBUG: ${{secrets.DEBUG}}
    - name: Download Composer cache dependencies from cache
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ matrix.os }}-composer-
    
    - name: Create mongodb replica set and wait to accept connections
      run: |
        docker run --name mongodb --publish 27017:27017 --detach mongo:${{ matrix.mongodb }} mongod --replSet rs

        COUNTER=0
        until docker exec --tty mongodb mongo --eval "db.serverStatus()"
        do
          sleep 1
          echo "."
          COUNTER=$((COUNTER+1))

          if [[ ${COUNTER} -eq 20 ]]; then
            echo "MongoDB did not initialize within 20 seconds. Exiting."
            exit 2
          fi
        done
        
        sudo docker exec --tty mongodb mongo --eval "rs.initiate({\"_id\":\"rs\",\"members\":[{\"_id\":0,\"host\":\"127.0.0.1\" }] })"
    - name: Install dependencies
      run: |
        composer install --no-interaction
    - name: Run tests
      run: |
        ./vendor/bin/phpunit --coverage-clover coverage.xml
      env:
        MONGO_HOST: 0.0.0.0
        MYSQL_HOST: 0.0.0.0
        MYSQL_PORT: 3307
    - name: Send coveralls
      run: vendor/bin/coveralls coverage.xml
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
